group.all_automations:
  friendly_name: "All Automations"
  hidden: false

group.fireplace:
  emulated_hue_hidden: true

sensor.garage_humidity:
  icon: "mdi:water-percent"

sensor.garage_luminance:
  icon: "mdi:brightness-5"

switch.fireplace:
  icon: "mdi:radiator"

switch.front_lights:
  icon: "mdi:lightbulb"

switch.living_room_floor_light:
  icon: "mdi:lightbulb"

switch.living_room_table_light:
  icon: "mdi:lightbulb"

light.fireplace_light:
  icon: "mdi:lightbulb"

switch.sitting_room_floor_light:
  icon: "mdi:lightbulb"

switch.sitting_room_stair_light:
  icon: "mdi:lightbulb"

switch.office_light:
  icon: "mdi:lightbulb"

switch.kitchen_speaker_plug:
  icon: "mdi:speaker"

switch.coffee_bar_light:
  icon: "mdi:lightbulb"

switch.kitchen_island:
  icon: "mdi:lightbulb"

switch.kitchen_outer_recessed:
  icon: "mdi:lightbulb"

switch.kitchen_inner_recessed:
  icon: "mdi:lightbulb"

switch.kitchen_table:
  icon: "mdi:lightbulb"