group.all_automations:
  friendly_name: "All Automations"
  hidden: false

group.fireplace:
  emulated_hue_hidden: true

sensor.garage_humidity:
  icon: "mdi:water-percent"

sensor.garage_luminance:
  icon: "mdi:brightness-5"

switch.fireplace:
  icon: "mdi:radiator"

switch.front_lights:
  icon: "mdi:lightbulb"

switch.living_room_floor_light:
  icon: "mdi:lightbulb"

switch.living_room_table_light:
  icon: "mdi:lightbulb"

switch.fireplace_light:
  icon: "mdi:lightbulb"

switch.sitting_room_floor_light:
  icon: "mdi:lightbulb"

switch.sitting_room_stair_light:
  icon: "mdi:lightbulb"

switch.office_light:
  icon: "mdi:lightbulb"