binary_sensor:
  - platform: mqtt
    name: "Garage Motion"
    state_topic: "home/garage/motion"
    device_class: "motion"
    payload_on: 255
    payload_off: 0

  - platform: mqtt
    name: "Basement Pantry Water Sensor"
    state_topic: "home/basement/pantry/water_sensor/state"
    device_class: "moisture"
    payload_on: 255
    payload_off: 0

  - platform: mqtt
    name: "Basement Pantry Water Sensor Battery"
    state_topic: "home/basement/pantry/water_sensor_battery/state"
    device_class: "battery"
    payload_on: 255

sensor:
  - platform: mqtt
    name: "Garage Temperature"
    unit_of_measurement: "°F"
    state_topic: "home/garage/temperature"

  - platform: mqtt
    name: "Garage Humidity"
    unit_of_measurement: "%"
    state_topic: "home/garage/humidity"

  - platform: mqtt
    name: "Garage Luminance"
    unit_of_measurement: "Lux"
    state_topic: "home/garage/luminance"