sensor:
  - platform: mqtt
    name: "Welcome Home"
    state_topic: "scene/welcome_home"
    expire_after: 30

  - platform: mqtt
    name: "Prep House for Occupancy Trigger"
    state_topic: "scene/occupy_home"
    expire_after: 30

  - platform: google_travel_time
    name: amanda_distance_from_home
    api_key: !secret google_travel_time_api_key
    origin: device_tracker.amanda_arodiphone
    destination: zone.home

  - platform: google_travel_time
    name: larry_distance_from_home
    api_key: !secret google_travel_time_api_key
    origin: device_tracker.larry_iphone6s
    destination: zone.home
  

automation:
  - id: prep_house_for_occupancy
    alias: "Prep House for Occupancy"
    trigger:
      - platform: state
        entity_id: sensor.prep_house_for_occupancy_trigger
        to: 'true'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: media_player.first_floor
          state: 'off'
    action:
      - service: media_player.turn_on
        entity_id: media_player.first_floor

  - id: welcome_home_amanda
    alias: Welcome Home Amanda
    trigger:
      - platform: state
        entity_id: sensor.welcome_home
        to: 'Amanda'

    action:
      - service: script.janet_speech_engine
        data:
          call_welcome_home: 1
          person: Amanda

  - id: welcome_home_larry
    alias: Welcome Home Larry
    trigger:
      - platform: state
        entity_id: sensor.welcome_home
        to: 'Larry'

    action:
      - service: script.janet_speech_engine
        data:
          call_welcome_home: 1
          person: Larry

  - id: welcome_home_both
    alias: Welcome Home Both
    trigger:
      - platform: state
        entity_id: sensor.welcome_home
        to: 'Both'

    action:
      - service: script.janet_speech_engine
        data:
          CustomMessage: "Welcome home, Amanda and Larry!"